version: '3.6'
services:
  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'appdb'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command:
      - redis-server
      - --save 60 1
      - --loglevel warning
  vault:
    image: vault:1.13.3
    ports:
      - "8200:8200"
    volumes:
      - vault_data:/vault/file
      - vault_data:/vault/logs
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "myroot"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    command: server -dev
volumes:
  db_data:
  redis_data:
  vault_data:
